name: "Cachix"
on:
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - uses: cachix/cachix-action@v15
        with:
          name: kaeeraa
          # If you chose signing key for write access
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

      - run: nix-build

      - run: nix-shell --run "echo OK" # actually useless 10 minutes
